---
- hosts: Routers
  connection: local
  vars_files:
    - /etc/ansible/secrets.yaml

  vars:
    connection:
      host: "{{ ansible_host }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      auth_pass: "{{ creds['auth_pass'] }}"
      authorize: yes

  tasks:

#   - name: obtain vars for vlans
#     include_vars: /etc/ansible/secrets.yaml
#
#   - name: define provider
#     set_fact:
#       connection:
#         authorize: yes
#        host: "{{ ansible_host }}"
#        username: "{{ creds['username'] }}"
#        password: "{{ creds['password'] }}"

   - name: ____Show run____
     ios_command:
       commands:
         - show run
       provider: "{{ connection }}"
     register: config

   - name: new variable with current date time
     set_fact: temp="{{lookup('pipe','date \"+%Y-%m-%d_%H:%M\"')}}"


   - name: ____ Save output to /etc/ansible/backups/Running-config ____
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "/etc/ansible/backups/Running-config/{{ inventory_hostname }}_Running-config_{{temp}}.txt"

