---
- hosts: Routers
  connection: local

  tasks:

   - name: obtain vars for vlans
     include_vars: /etc/ansible/secrets.yaml

   - name: ____define provider____
     set_fact:
       connection:
         authorize: yes
         host: "{{ ansible_host }}"
         username: "{{ creds['username'] }}"
         password: "{{ creds['password'] }}"

   - name: ____Configure banner from file____
     ios_banner:
       banner: motd
       text: "{{ lookup('file', '/etc/ansible/Vars/raw_banner.cfg') }}"
       state: present
       provider: "{{ connection }}"

   - name: ____Save running to startup when modified____
     ios_config:
       save_when: modified
       host: "{{ ansible_host }}"
       provider: "{{ connection }}"


#   - name: remove the login banner
#     ios_banner:
#       banner: login
#       state: absent
#       host: "{{ ansible_host }}"
#       username: ansible
#       password: *******
#   - name: remove the exec banner
#     ios_banner:
#       banner: exec
#       state: absent
#       host: "{{ ansible_host }}"
#       username: ansible
#       password: *******
#   - name: remove the incoming banner
#     ios_banner:
#       banner: incoming
#       state: absent
#       host: "{{ ansible_host }}"
#       username: ansible
#       password: *******
